Repository asksa1256/codeit-intermidiate-project, pull requests merged in 2025-08, with the labels that each got.

#238 css 수정
  src/components/feature/Keyboards/Filter/FilterModal.tsx
Labels: style ✨

#249 Refactor: 마이프로필 QA 수정
  src/components/feature/myProfile/MyKeyboardArea.tsx
  src/components/feature/myProfile/MyprofileMain.tsx
  src/components/feature/myProfile/MyprofileSidebar.tsx
Labels: Refactor 🔄

#254 fix: 별점 정보가 상단에 고정될 때만 키보드 이름 표시하도록 변경
  src/components/feature/keyboardDetails/RatingsInfo.tsx
Labels: bug 😵

#255 fix:상세페이지 진입시 이전 페이지의 스크롤을 초기화해서 화면 상단부터 시작하도록 변경
  src/app/(global)/keyboards/[keyboardid]/page.tsx
Labels: bug 😵

#262 chore: 이미지 임시 인코딩 코드 삭제
  src/components/feature/keyboardDetails/KeyboardInfoCard.tsx
Labels: chore

#264 fix: 가격 필터 슬라이더 초기화 안되는 문제 수정
  src/components/feature/Keyboards/Filter/FilterContent.tsx
  src/components/ui/RangeSlider/MultihandleSlider.tsx
  src/types/rangeSliderTypes.d.ts
Labels: bug 😵

#266 Refactor: 마이프로필 페이지
  src/app/(global)/myprofile/page.tsx
  src/components/feature/Keyboards/KeyboardsList.tsx
  src/components/feature/myProfile/MyKeyboardArea.tsx
  src/components/feature/myProfile/MyProfileContents.tsx
  src/components/feature/myProfile/MyReviewArea.tsx
  src/components/feature/myProfile/Myprofile.tsx
  src/components/feature/myProfile/MyprofileSidebar.tsx
Labels: Refactor 🔄

#267 Fix: 아이폰에서 호버클릭 안되는 이슈 해결
  src/components/feature/Keyboards/Filter/FilterContent.tsx
  src/components/ui/InfoGuide.tsx
Labels: bug 😵
