Repository asksa1256/codeit-intermidiate-project, pull requests merged in 2025-07, with the labels that each got.

#57 #54 상대적 시간계산 유틸함수 추가
  src/utils/formatters.ts
Labels: feature ✨

#55 feature: 공용 모달창 제작
  eslint.config.mjs
  package-lock.json
  src/app/(global)/keyboards/page.tsx
  src/app/confirmmodal-test/page.tsx
  src/app/layout.tsx
  src/app/modal-test/page.tsx
  src/assets/icons/CloseIcon.svg
  src/components/feature/ConfirmModal.tsx
  src/components/feature/Modal.tsx
Labels: feature ✨, style ✨

#66 feat:별점 포매팅 유틸함수 구현, 가격과 별점 표기 컴포넌트 구현(#62)
  public/images/StarIcon.svg
  src/components/ui/RatingAndPrice.tsx
  src/utils/formatters.ts
Labels: style ✨, 컴포넌트

#88 #74 간편 로그인 구현 (카카오 로그인)
  src/app/(auth)/oauth/kakao/page.tsx
  src/app/globals.css
  src/components/feature/KakaoLoginButton.tsx
  src/components/feature/LoginForm.tsx
  src/components/feature/RequireAuth.tsx
  src/constants/index.ts
  src/lib/api/apiClient.ts
  src/lib/api/axios.ts
Labels: feature ✨

#100 feat: 별점 집계바 컴포넌트,별점 인풋 컴포넌트 구현(#82)
  src/components/ui/RangeSlider/RatingRangeBars.tsx
  src/components/ui/StarRatingInput.tsx
Labels: feature ✨, style ✨, 컴포넌트

#102 feat: 아로마 배열을 키보드 컬러 배열로 매핑하는 유틸함수 구현(#101)
  src/utils/convertToColorArray.ts
Labels: feature ✨

#104 Fix: KeyboardThumbnail 컴포넌트 수정
  next.config.ts
  src/app/globals.css
  src/components/ui/KeyboardThumbnail.tsx
Labels: bug 😵

#119 Fix: 로그인 권한에 따른 페이지 리다이렉트 오작동 수정
  src/components/feature/RequireAuth.tsx
  src/constants/index.ts
Labels: bug 😵

#122 #118 로그인 권한 페이지 - 로그인 후 자동 리다이렉트
  src/components/feature/LoginForm.tsx
  src/components/feature/RequireAuth.tsx
Labels: feature ✨

#129 Feat: 사이드바(유저 프로필 영역) 컴포넌트 기능 구현
  src/components/feature/myProfile/MyprofileSidebar.tsx
  src/lib/api/apiClient.ts
Labels: feature ✨

#136 feat: 데이터 없을 때 렌더링 UI 컴포넌트 제작
  public/images/EmptyListIcon.svg
  src/components/ui/EmptyList.tsx
Labels: style ✨, 컴포넌트

#148 Refactor: 로그인, 회원가입 입력값 처리 방식 개선 (trim 추가)
  src/components/feature/LoginForm.tsx
  src/components/feature/SignUpForm.tsx
Labels: Refactor 🔄

#139 #124 유저 전역 상태 추가 및 프로필 페이지에 적용
  package-lock.json
  package.json
  src/app/(auth)/oauth/kakao/page.tsx
  src/components/feature/LoginForm.tsx
  src/components/feature/RequireAuth.tsx
  src/components/feature/SignUpForm.tsx
  src/components/feature/myProfile/MyprofileSidebar.tsx
  src/constants/index.ts
  src/lib/api/apiClient.ts
  src/stores/authStore.ts
  src/types/types.d.ts
  src/types/userTypes.d.ts
Labels: feature ✨, chore

#142 #60 상세 페이지 퍼블리싱
  public/images/DownArrowIcon.svg
  public/images/UpArrowIcon.svg
  src/app/(global)/keyboards/[keyboardid]/page.tsx
  src/app/globals.css
  src/assets/icons/HeartIcon.svg
  src/components/feature/keyboardDetails/KeyboardInfoCard.tsx
  src/components/feature/keyboardDetails/RatingsInfo.tsx
  src/components/feature/keyboardDetails/ReviewCard.tsx
  src/components/feature/keyboardDetails/ReviewList.tsx
  src/components/ui/KeyboardColorTags.tsx
  src/components/ui/RangeSlider/KeyboardProperties.tsx
  src/components/ui/RangeSlider/RatingRangeBars.tsx
  src/utils/formatters.ts
Labels: feature ✨, style ✨

#145 Feat: myprofile 페이지 리뷰 영역 기능 구현
  src/components/feature/myProfile/MyReviewArea.tsx
  src/components/feature/myProfile/MyReviewItem.tsx
  src/components/feature/myProfile/MyReviewList.tsx
  src/components/feature/myProfile/MyprofileMain.tsx
  src/components/feature/myProfile/MyprofileSidebar.tsx
  src/components/ui/StarRatingInput.tsx
Labels: feature ✨

#149 Feat: myprofile 페이지 키보드 영역 기능 구현
  src/app/(global)/myprofile/page.tsx
  src/components/feature/ConfirmModal.tsx
  src/components/feature/myProfile/MyKeyboardArea.tsx
  src/components/feature/myProfile/MyKeyboardItem.tsx
  src/components/feature/myProfile/MyKeyboardList.tsx
  src/components/feature/myProfile/MyListLoading.tsx
  src/components/feature/myProfile/MyProfileContents.tsx
  src/components/feature/myProfile/MyReviewArea.tsx
  src/components/feature/myProfile/Myprofile.tsx
  src/components/feature/myProfile/MyprofileMain.tsx
Labels: feature ✨

#188 무한 스크롤 훅 #187
  public/images/DescriptionCard2.png
  public/images/HeroKeyboardCard1.png
  public/images/HeroKeyboardCardL2.png
  public/images/HeroKeyboardCardL3.png
  public/images/HeroKeyboardCardR2.png
  public/images/HeroKeyboardCardR3.png
  public/images/LandingFilter.png
  public/images/RecommendCard1.png
  public/images/RecommendCard2.png
  public/images/ReviewCard.png
  src/app/(global)/page.tsx
  src/components/feature/keyboardDetails/ReviewCard.tsx
  src/components/feature/keyboardDetails/ReviewList.tsx
  src/components/ui/LandingPage/HeroImage.tsx
  src/components/ui/LandingPage/LandingPageCard.tsx
  src/components/ui/LandingPageCard.tsx
  src/hooks/useIntersectionObserver.ts
Labels: feature ✨

#186 Feat: myprofile 키보드 수정 API 연동
  src/components/feature/myProfile/MyKeyboardArea.tsx
  src/components/feature/myProfile/MyKeyboardItem.tsx
  src/components/feature/myProfile/MyKeyboardList.tsx
  src/components/feature/myProfile/MyReviewArea.tsx
  src/components/feature/reviewForm/ReviewFormCheckboxItem.tsx
  src/components/ui/Dropdown/DdButtonItem.tsx
  src/components/ui/Dropdown/DropdownWithSelectButton/index.tsx
  src/utils/convertToTypeArray.ts
Labels: feature ✨

#226 상세페이지 기능 구현 #60
  src/app/(global)/keyboards/[keyboardid]/page.tsx
  src/components/feature/keyboardDetails/RatingsInfo.tsx
  src/components/feature/keyboardDetails/ReviewCard.tsx
  src/components/feature/keyboardDetails/ReviewList.tsx
  src/components/feature/myProfile/MyReviewItem.tsx
  src/components/feature/reviewForm/ReviewForm.tsx
Labels: feature ✨, style ✨

#234 Chore: 마이프로필 페이지 수정
  src/components/feature/keyboardDetails/RatingsInfo.tsx
  src/components/feature/keyboardDetails/ReviewCard.tsx
  src/components/feature/keyboardDetails/ReviewList.tsx
  src/components/feature/myProfile/MyKeyboardItem.tsx
  src/components/feature/myProfile/MyReviewArea.tsx
  src/components/feature/myProfile/MyReviewItem.tsx
  src/components/feature/reviewForm/ReviewForm.tsx
Labels: chore

#236 Feature/style keyboard list
  src/app/(global)/keyboards/page.tsx
  src/app/(global)/keyboards_back/page.tsx
  src/components/feature/Keyboards/Filter/FilterFooterButton.tsx
  src/components/feature/Keyboards/Filter/FilterModal.tsx
  src/components/feature/Keyboards/Filter/FilterModalBack.tsx
  src/components/feature/Keyboards/Filter/FilterOpenButton.tsx
  src/components/feature/Keyboards/IndexKeyboardsCard.tsx
  src/components/feature/Keyboards/KeyboardsArea.tsx
Labels: style ✨
